# Generated by Django 3.0.3 on 2020-02-28 14:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Nom du projet')),
                ('objective', models.TextField(max_length=4000, verbose_name='Objectif stratégique')),
                ('starting_date', models.DateField(default=datetime.date.today, verbose_name='Date de commencement')),
                ('ending_date', models.DateField(default=datetime.date.today, verbose_name='Date de fin')),
                ('hourly_volume', models.SmallIntegerField(verbose_name='Volume horaire à consacrer')),
                ('forces', models.TextField(max_length=8000, verbose_name='Forces')),
                ('weaknesses', models.TextField(max_length=8000, verbose_name='Faiblesses')),
                ('opportunities', models.TextField(max_length=8000, verbose_name='Opportunités')),
                ('menaces', models.TextField(max_length=8000, verbose_name='Menaces')),
                ('offensive', models.TextField(max_length=8000, verbose_name='Offensive')),
                ('defensive', models.TextField(max_length=8000, verbose_name='Défensive')),
                ('preventive', models.TextField(max_length=8000, verbose_name='Préventive')),
                ('emergency', models.TextField(max_length=8000, verbose_name='Urgence')),
                ('step_1', models.CharField(max_length=2000, verbose_name='Activité 1')),
                ('step_2', models.CharField(max_length=2000, verbose_name='Activité 2')),
                ('step_3', models.CharField(blank=True, max_length=2000, verbose_name='Activité 3')),
                ('step_4', models.CharField(blank=True, max_length=2000, verbose_name='Activité 4')),
                ('step_5', models.CharField(blank=True, max_length=2000, verbose_name='Activité 5')),
                ('step_6', models.CharField(blank=True, max_length=2000, verbose_name='Activité 6')),
            ],
        ),
        migrations.CreateModel(
            name='SavedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sauvegardé par')),
                ('saved_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Profile', verbose_name='Profil sauvegardé')),
            ],
        ),
        migrations.AddConstraint(
            model_name='savedprofile',
            constraint=models.UniqueConstraint(fields=('saved_by', 'saved_profile'), name='saved_association'),
        ),
    ]
