# Generated by Django 3.0.3 on 2020-02-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='step_1_duration',
            field=models.SmallIntegerField(default=1, verbose_name='Volume horaire par semaine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='step_2_duration',
            field=models.SmallIntegerField(default=1, verbose_name='Volume horaire par semaine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='step_3_duration',
            field=models.SmallIntegerField(default=1, verbose_name='Volume horaire par semaine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='step_4_duration',
            field=models.SmallIntegerField(default=1, verbose_name='Volume horaire par semaine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='step_5_duration',
            field=models.SmallIntegerField(default=1, verbose_name='Volume horaire par semaine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='step_6_duration',
            field=models.SmallIntegerField(default=1, verbose_name='Volume horaire par semaine'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hourly_volume',
            field=models.SmallIntegerField(verbose_name='Volume horaire total à consacrer par semaine'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='step_3',
            field=models.CharField(max_length=2000, verbose_name='Activité 3'),
        ),
    ]
