# Generated by Django 3.0.3 on 2020-03-07 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weorganization', '0002_auto_20200228_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ending_time',
            field=models.TimeField(default=datetime.datetime(2020, 3, 7, 22, 22), verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='starting_time',
            field=models.TimeField(default=datetime.datetime(2020, 3, 7, 18, 8), verbose_name='Heure de début'),
        ),
    ]
