# Generated by Django 3.0.3 on 2020-02-28 14:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import weorganization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200, verbose_name='Activité')),
                ('resource', models.CharField(max_length=200, verbose_name='Ressource')),
                ('starting_time', models.TimeField(default=datetime.datetime(2020, 2, 28, 15, 25), verbose_name='Heure de début')),
                ('ending_time', models.TimeField(default=datetime.datetime(2020, 2, 28, 22, 22), verbose_name='Heure de fin')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activity', django_enumfield.db.fields.EnumField(enum=weorganization.models.ActivityTypeList)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', django_enumfield.db.fields.EnumField(enum=weorganization.models.DayList)),
                ('daily_activity', models.ForeignKey(default='99999', on_delete=django.db.models.deletion.CASCADE, to='weorganization.Activity', verbose_name='Activité liée')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Profile', verbose_name='Profil lié')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur lié')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weorganization.ActivityType', verbose_name='type'),
        ),
    ]
